version: '3.7'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: